name: try 

run-name: ${{ github.actor }}
on: 
  push:
    branches:
      - 'main'
      - 'testing'
jobs:
  miniCanvasTestsActions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: upgrade pip
        working-directory: ./
        run: python -m pip install --upgrade pip
      - name: install requirements
        working-directory: ./
        run: pip install -r requirements.txt
      - name: run tests
        working-directory: ./
        run: pytest             